const levelClass = {
  GREEN: "healthy",
  YELLOW: "warning",
  ORANGE: "warning",
  RED: "critical",
};

const levelLabel = {
  GREEN: "INFO - Stable",
  YELLOW: "WARNING - Attention Required",
  ORANGE: "WARNING - High Risk",
  RED: "CRITICAL - Intervention Required",
};

const telemetryHistory = {
  vibration: [],
  temperature: [],
  risk: [],
  health: [],
  decisions: [],
  startedAt: Date.now(),
  lastLevel: "GREEN",
};

let lastData = null;
let refreshTimer = null;
let refreshMs = 5000;
let trendWindow = 30;
let isPaused = false;

const views = {
  dashboard: {
    eyebrow: "Enterprise Reliability Console",
    title: "Predictive Maintenance Overview",
    description: "Autonomous monitoring, RUL prediction, failure simulation, and maintenance planning.",
  },
  monitoring: {
    eyebrow: "Live Monitoring",
    title: "Machine Telemetry Stream",
    description: "Realtime synchronized sensor signals and the latest telemetry register from the active machine.",
  },
  predictions: {
    eyebrow: "Prediction Engine",
    title: "Failure Forecast and RUL Projection",
    description: "Remaining useful life, failure probability, and future degradation timeline generated by Hermes.",
  },
  analytics: {
    eyebrow: "Operational Analytics",
    title: "Risk Factor Analysis",
    description: "Composite view of anomaly score, bearing wear, thermal pressure, lubricant condition, and health trend.",
  },
  reports: {
    eyebrow: "Reports",
    title: "Maintenance Report Center",
    description: "Generate professional PDF reports for reliability teams, plant managers, and executive review.",
  },
  alerts: {
    eyebrow: "Alert Operations",
    title: "Alert Timeline and Policy",
    description: "Track current alert state, recent escalations, and operational response categories.",
  },
  settings: {
    eyebrow: "Settings",
    title: "Platform Configuration",
    description: "Control demo refresh behavior and review current industrial AI platform status.",
  },
};

function numeric(value) {
  const number = Number(value);
  return Number.isFinite(number) ? number : null;
}

function labelize(key) {
  return key.replaceAll("_", " ").replace(/\b\w/g, char => char.toUpperCase());
}

function cssVar(name) {
  return getComputedStyle(document.documentElement).getPropertyValue(name).trim();
}

function getSensorValue(sensorData, ...keys) {
  for (const key of keys) {
    const value = numeric(sensorData[key]);
    if (value !== null) return value;
  }
  return 0;
}

function setupCanvas(canvas) {
  const rect = canvas.getBoundingClientRect();
  if (rect.width < 20 || rect.height < 20) return null;
  const ratio = window.devicePixelRatio || 1;
  canvas.width = Math.max(1, Math.floor(rect.width * ratio));
  canvas.height = Math.max(1, Math.floor(rect.height * ratio));
  const ctx = canvas.getContext("2d");
  ctx.setTransform(ratio, 0, 0, ratio, 0, 0);
  return { ctx, width: rect.width, height: rect.height };
}

function drawHealth(value, level) {
  const canvas = document.getElementById("healthCanvas");
  const canvasSetup = setupCanvas(canvas);
  if (!canvasSetup) return;
  const { ctx, width, height } = canvasSetup;
  const centerX = width / 2;
  const centerY = height / 2;
  const radius = Math.min(width, height) / 2 - 10;
  const start = Math.PI * 0.78;
  const end = Math.PI * 2.22;
  const percentEnd = start + (end - start) * (Math.max(0, Math.min(100, value)) / 100);
  const color = cssVar(`--${levelClass[level] || "healthy"}`);

  ctx.clearRect(0, 0, width, height);
  ctx.lineCap = "round";
  ctx.lineWidth = 12;
  ctx.strokeStyle = "#263645";
  ctx.beginPath();
  ctx.arc(centerX, centerY, radius, start, end);
  ctx.stroke();

  ctx.strokeStyle = color;
  ctx.beginPath();
  ctx.arc(centerX, centerY, radius, start, percentEnd);
  ctx.stroke();

  ctx.lineWidth = 1;
  ctx.strokeStyle = "rgba(183,196,207,0.28)";
  for (let i = 0; i <= 10; i += 1) {
    const angle = start + ((end - start) / 10) * i;
    const inner = radius - 18;
    const outer = radius - 8;
    ctx.beginPath();
    ctx.moveTo(centerX + Math.cos(angle) * inner, centerY + Math.sin(angle) * inner);
    ctx.lineTo(centerX + Math.cos(angle) * outer, centerY + Math.sin(angle) * outer);
    ctx.stroke();
  }
}

function drawLineChart(canvasId, series, options) {
  const canvas = document.getElementById(canvasId);
  if (!canvas) return;
  const canvasSetup = setupCanvas(canvas);
  if (!canvasSetup) return;
  const { ctx, width, height } = canvasSetup;
  const padding = { left: 42, right: 18, top: 18, bottom: 30 };
  const plotW = width - padding.left - padding.right;
  const plotH = height - padding.top - padding.bottom;
  const normalizedSeries = series.map(item => ({
    ...item,
    values: normalizeSeries(item.values, options.points),
  }));
  const allValues = normalizedSeries.flatMap(item => item.values);
  const min = options.min ?? Math.min(...allValues, 0);
  const max = options.max ?? Math.max(...allValues, 1);
  const scaleY = value => padding.top + plotH - ((value - min) / Math.max(1, max - min)) * plotH;
  const scaleX = index => padding.left + (index / Math.max(1, options.points - 1)) * plotW;

  ctx.clearRect(0, 0, width, height);
  ctx.strokeStyle = "rgba(148,163,184,0.16)";
  ctx.lineWidth = 1;
  ctx.fillStyle = cssVar("--muted");
  ctx.font = "12px Inter, system-ui";

  for (let i = 0; i <= 4; i += 1) {
    const y = padding.top + (plotH / 4) * i;
    ctx.beginPath();
    ctx.moveTo(padding.left, y);
    ctx.lineTo(width - padding.right, y);
    ctx.stroke();
  }

  ctx.fillText(String(Math.round(max)), 6, padding.top + 4);
  ctx.fillText(String(Math.round(min)), 6, padding.top + plotH);

  normalizedSeries.forEach(item => {
    ctx.strokeStyle = item.color;
    ctx.lineWidth = 2;
    ctx.beginPath();
    item.values.forEach((value, index) => {
      const x = scaleX(index);
      const y = scaleY(value);
      if (index === 0) ctx.moveTo(x, y);
      else ctx.lineTo(x, y);
    });
    ctx.stroke();
    item.values.forEach((value, index) => {
      const x = scaleX(index);
      const y = scaleY(value);
      ctx.fillStyle = item.color;
      ctx.beginPath();
      ctx.arc(x, y, item.values.length <= 8 ? 3.2 : 2.2, 0, Math.PI * 2);
      ctx.fill();
    });
  });

  let legendX = padding.left;
  normalizedSeries.forEach(item => {
    ctx.fillStyle = item.color;
    ctx.fillRect(legendX, height - 16, 10, 3);
    ctx.fillStyle = cssVar("--text-soft");
    ctx.fillText(item.label, legendX + 15, height - 11);
    legendX += 118;
  });
}

function normalizeSeries(values, points) {
  const clean = values.filter(value => Number.isFinite(value));
  if (clean.length === 0) return Array.from({ length: points }, () => 0);
  if (clean.length >= points) return clean.slice(-points);
  const first = clean[0];
  const prefix = Array.from({ length: points - clean.length }, (_, index) => {
    const wave = Math.sin(index * 0.7) * Math.max(0.8, Math.abs(first) * 0.015);
    return Math.max(0, first + wave);
  });
  return [...prefix, ...clean];
}

function drawFutureTimeline(points) {
  const normalized = points.map(point => ({
    ...point,
    risk_percent: point.failure_probability * 100,
  }));
  drawLineChart("timelineCanvas", [
    { label: "Health", color: cssVar("--accent"), values: normalized.map(point => point.health_percent) },
    { label: "Failure risk", color: cssVar("--critical"), values: normalized.map(point => point.risk_percent) },
  ], { min: 0, max: 100, points: normalized.length });
}

function drawSensorHistory() {
  drawLineChart("sensorCanvas", [
    { label: "Vibration", color: cssVar("--accent"), values: telemetryHistory.vibration },
    { label: "Temperature", color: cssVar("--warning"), values: telemetryHistory.temperature },
    { label: "Risk", color: cssVar("--critical"), values: telemetryHistory.risk },
  ], { min: 0, max: Math.max(100, ...telemetryHistory.temperature, ...telemetryHistory.risk, ...telemetryHistory.vibration), points: trendWindow });
}

function drawMonitoringHistory() {
  if (!document.getElementById("monitoringCanvas")) return;
  drawLineChart("monitoringCanvas", [
    { label: "Vibration x10", color: cssVar("--accent"), values: telemetryHistory.vibration },
    { label: "Temperature", color: cssVar("--warning"), values: telemetryHistory.temperature },
    { label: "Failure risk", color: cssVar("--critical"), values: telemetryHistory.risk },
  ], { min: 0, max: Math.max(100, ...telemetryHistory.temperature, ...telemetryHistory.risk, ...telemetryHistory.vibration), points: trendWindow });
}

function drawPredictionChart(data) {
  if (!data || !document.getElementById("predictionCanvas")) return;
  const points = data.future.timeline;
  drawLineChart("predictionCanvas", [
    { label: "Health", color: cssVar("--accent"), values: points.map(point => point.health_percent) },
    { label: "Failure risk", color: cssVar("--critical"), values: points.map(point => point.failure_probability * 100) },
    { label: "Vibration x10", color: cssVar("--warning"), values: points.map(point => point.vibration_rms_mm_s * 10) },
  ], { min: 0, max: 100, points: points.length });
}

function drawAnalyticsChart() {
  if (!document.getElementById("analyticsCanvas")) return;
  drawLineChart("analyticsCanvas", [
    { label: "Health", color: cssVar("--healthy"), values: telemetryHistory.health },
    { label: "Risk", color: cssVar("--critical"), values: telemetryHistory.risk },
  ], { min: 0, max: 100, points: trendWindow });
}

function pushHistory(sensorData, risk, health) {
  const vibration = getSensorValue(sensorData, "vibration_rms_mm_s", "vibration_sensor");
  const temperature = getSensorValue(sensorData, "temperature_c", "temperature_sensor");
  telemetryHistory.vibration.push(vibration * 10);
  telemetryHistory.temperature.push(temperature);
  telemetryHistory.risk.push(risk);
  telemetryHistory.health.push(health);
  Object.keys(telemetryHistory).forEach(key => {
    if (Array.isArray(telemetryHistory[key])) telemetryHistory[key] = telemetryHistory[key].slice(-trendWindow);
  });
}

function renderSensors(sensorData) {
  const keys = Object.keys(sensorData).filter(key => numeric(sensorData[key]) !== null).slice(0, 8);
  document.getElementById("sensorGrid").innerHTML = keys.map(key => {
    const value = numeric(sensorData[key]);
    return `<div class="sensorTile"><small>${labelize(key)}</small><strong>${value.toFixed(2)}</strong></div>`;
  }).join("");
}

function renderRiskMatrix(data) {
  const signals = data.anomaly.signals || {};
  const cells = [
    ["Anomaly Score", data.anomaly.anomaly_score * 100, "%"],
    ["Bearing Wear", signals.bearing_wear || 0, "%"],
    ["Thermal Load", Math.min(100, ((signals.temperature || 0) / 90) * 100), "%"],
    ["Lubricant Loss", Math.max(0, 100 - (signals.lubricant_quality || 100)), "%"],
  ];
  document.getElementById("riskMatrix").innerHTML = cells.map(([label, value, suffix]) => {
    const safeValue = Math.max(0, Math.min(100, value));
    return `<div class="riskCell"><span>${label}</span><strong>${safeValue.toFixed(0)}${suffix}</strong><div class="miniBar"><div style="width:${safeValue}%"></div></div></div>`;
  }).join("");
  const analyticsMatrix = document.getElementById("analyticsRiskMatrix");
  if (analyticsMatrix) {
    analyticsMatrix.innerHTML = document.getElementById("riskMatrix").innerHTML;
  }
}

function renderLogs(logs) {
  document.getElementById("logStream").innerHTML = logs.slice(0, 10).map(log =>
    `<div class="logItem"><b>${log.timestamp}</b>${log.message}</div>`
  ).join("");
}

function renderThoughts(thoughts) {
  document.getElementById("thoughts").innerHTML = thoughts.map(text =>
    `<div class="thoughtItem">${text}</div>`
  ).join("");
}

function renderAlerts(alerts, current) {
  const allAlerts = [current, ...alerts].filter(Boolean).slice(0, 8);
  document.getElementById("alerts").innerHTML = allAlerts.map(alert => {
    const cls = levelClass[alert.level] || "info";
    return `<div class="alertItem ${cls}"><b>${alert.level}</b>${alert.message}<br><small>${alert.timestamp || ""}</small></div>`;
  }).join("");
}

function renderDecisions(data) {
  const cls = levelClass[data.alert_level] || "info";
  telemetryHistory.decisions.unshift({
    level: data.alert_level,
    cls,
    action: data.decision.action,
    time: new Date(data.timestamp).toLocaleTimeString(),
  });
  telemetryHistory.decisions = telemetryHistory.decisions.slice(0, 6);
  document.getElementById("decisions").innerHTML = telemetryHistory.decisions.map(item =>
    `<div class="decisionItem ${item.cls}"><b>${item.time}</b>${item.action}</div>`
  ).join("");
}

function renderSensorTable(sensorData) {
  const table = document.getElementById("sensorTable");
  if (!table) return;
  table.innerHTML = Object.keys(sensorData)
    .filter(key => numeric(sensorData[key]) !== null)
    .map(key => {
      const value = numeric(sensorData[key]);
      const unit = key.includes("temperature") ? "C" : key.includes("rpm") ? "RPM" : key.includes("percent") ? "%" : key.includes("vibration") ? "mm/s" : "-";
      return `<tr><td>${labelize(key)}</td><td>${value.toFixed(3)}</td><td>${unit}</td></tr>`;
    })
    .join("");
}

function renderPredictionSummary(data) {
  const target = document.getElementById("predictionSummary");
  if (!target) return;
  target.innerHTML = `
    <div><b>Remaining Useful Life</b><span>${data.prediction.rul_hours.toFixed(1)} hours</span></div>
    <div><b>Failure Probability</b><span>${(data.failure_probability * 100).toFixed(1)}%</span></div>
    <div><b>Primary Failure Mode</b><span>${data.analysis.primary_failure_mode}</span></div>
    <div><b>Recommended Action</b><span>${data.decision.action}</span></div>
  `;
  document.getElementById("predictionHorizon").textContent = `${data.future.estimated_death_timeline_hours} h`;
}

function renderReportSummary(data) {
  const target = document.getElementById("reportSummary");
  if (!target) return;
  target.innerHTML = `
    <div><b>Current Status</b><span>${levelLabel[data.alert_level] || "INFO - Stable"}</span></div>
    <div><b>Machine Health</b><span>${data.prediction.health_percent.toFixed(1)}%</span></div>
    <div><b>Maintenance Action</b><span>${data.decision.action}</span></div>
  `;
}

function renderSettingsSummary(data) {
  const target = document.getElementById("settingsSummary");
  if (!target) return;
  target.innerHTML = `
    <div><b>Hermes Agent</b><span>Connected and monitoring live machine data.</span></div>
    <div><b>Model</b><span>${data.prediction.model_name}</span></div>
    <div><b>Latest Sample</b><span>#${String(data.sample_index).padStart(3, "0")}</span></div>
    <div><b>Data Quality</b><span>${(data.data_quality.score * 100).toFixed(0)}% complete, prediction-ready: ${data.data_quality.ready_for_prediction ? "yes" : "no"}</span></div>
  `;
  const integration = document.getElementById("integrationSummary");
  if (integration) {
    integration.innerHTML = `
      <div><b>Current Source</b><span>${data.data_source.mode} - ${data.data_source.csv_path}</span></div>
      <div><b>Real Telemetry API</b><span>POST machine readings to /api/telemetry as JSON.</span></div>
      <div><b>Required Fields</b><span>vibration_rms_mm_s, temperature_c, rpm. Optional: acoustic_noise_db, bearing_wear_percent, lubricant_quality_percent.</span></div>
      <div><b>Tag Mapping</b><span>Configure plant tag names in config/machine_assets.json.</span></div>
    `;
  }
}

function renderAlertsPage(data) {
  const target = document.getElementById("alertsPageList");
  if (!target) return;
  const allAlerts = [data.alert, ...data.alerts].filter(Boolean).slice(0, 20);
  target.innerHTML = allAlerts.map(alert => {
    const cls = levelClass[alert.level] || "info";
    return `<div class="alertItem ${cls}"><b>${alert.level}</b>${alert.message}<br><small>${alert.timestamp || ""}</small></div>`;
  }).join("");
}

function applyAlert(level) {
  const cls = levelClass[level] || "info";
  const badge = document.getElementById("globalAlert");
  badge.className = `statusPill ${cls}`;
  badge.textContent = levelLabel[level] || "INFO - Stable";
  document.getElementById("topStatus").textContent = level === "GREEN" ? "Stable" : levelLabel[level].split("-")[1].trim();
  document.getElementById("decisionPriority").textContent = level === "GREEN" ? "INFO" : level;
  document.getElementById("notificationDot").style.background = cssVar(`--${cls}`);
}

function setUptime() {
  const seconds = Math.floor((Date.now() - telemetryHistory.startedAt) / 1000);
  const hh = String(Math.floor(seconds / 3600)).padStart(2, "0");
  const mm = String(Math.floor((seconds % 3600) / 60)).padStart(2, "0");
  const ss = String(seconds % 60).padStart(2, "0");
  document.getElementById("uptime").textContent = `${hh}:${mm}:${ss}`;
}

function switchView(viewName) {
  const selected = views[viewName] ? viewName : "dashboard";
  document.querySelectorAll("[data-view-panel]").forEach(panel => {
    panel.classList.toggle("activeView", panel.dataset.viewPanel === selected);
  });
  document.querySelectorAll(".sidebar a[data-view]").forEach(link => {
    link.classList.toggle("active", link.dataset.view === selected);
  });
  document.getElementById("viewEyebrow").textContent = views[selected].eyebrow;
  document.getElementById("viewTitle").textContent = views[selected].title;
  document.getElementById("viewDescription").textContent = views[selected].description;
  document.getElementById("sidebar").classList.remove("open");
  document.getElementById("overlay").classList.remove("open");
  requestAnimationFrame(() => redrawAll());
  window.setTimeout(redrawAll, 80);
}

function redrawAll() {
  drawHealth(telemetryHistory.health.at(-1) || 0, telemetryHistory.lastLevel);
  drawSensorHistory();
  drawMonitoringHistory();
  drawAnalyticsChart();
  if (lastData) {
    drawFutureTimeline(lastData.future.timeline);
    drawPredictionChart(lastData);
  }
}

function startRefreshTimer() {
  if (refreshTimer) clearInterval(refreshTimer);
  if (!isPaused) refreshTimer = setInterval(refresh, refreshMs);
}

async function refresh() {
  if (isPaused) return;
  const response = await fetch("/api/state");
  const data = await response.json();
  lastData = data;
  const health = data.prediction.health_percent;
  const risk = data.failure_probability * 100;
  const rul = data.prediction.rul_hours;

  pushHistory(data.sensor_data, risk, health);
  telemetryHistory.lastLevel = data.alert_level;
  applyAlert(data.alert_level);

  document.getElementById("sampleIndex").textContent = `Sample #${String(data.sample_index).padStart(3, "0")}`;
  document.getElementById("healthValue").textContent = `${health.toFixed(0)}%`;
  document.getElementById("healthDelta").textContent = data.prediction.model_name;
  document.getElementById("rulValue").textContent = `${rul.toFixed(1)} h`;
  document.getElementById("topRul").textContent = `${rul.toFixed(1)} h`;
  document.getElementById("topRisk").textContent = `${risk.toFixed(0)}%`;
  document.getElementById("riskValue").textContent = `${risk.toFixed(0)}%`;
  document.getElementById("riskMetric").textContent = `${risk.toFixed(0)}%`;
  document.getElementById("riskFill").style.width = `${Math.min(100, risk)}%`;
  document.getElementById("rulFill").style.width = `${Math.min(100, Math.max(0, health))}%`;
  document.getElementById("decisionText").textContent = data.decision.action;
  document.getElementById("decisionRationale").textContent = data.decision.rationale;
  document.getElementById("deathLine").textContent = `${data.future.estimated_death_timeline_hours} h to failure point`;

  renderSensors(data.sensor_data);
  renderSensorTable(data.sensor_data);
  renderRiskMatrix(data);
  renderLogs(data.logs);
  renderThoughts(data.thought_process);
  renderAlerts(data.alerts, data.alert);
  renderAlertsPage(data);
  renderDecisions(data);
  renderPredictionSummary(data);
  renderReportSummary(data);
  renderSettingsSummary(data);
  drawHealth(health, data.alert_level);
  drawSensorHistory();
  drawMonitoringHistory();
  drawAnalyticsChart();
  drawFutureTimeline(data.future.timeline);
  drawPredictionChart(data);
}

document.getElementById("reportButton").addEventListener("click", async () => {
  const response = await fetch("/api/report", { method: "POST" });
  const data = await response.json();
  const file = data.pdf_path.split(/[\\/]/).pop();
  window.location.href = `/reports/${file}`;
});

document.getElementById("reportButtonSecondary").addEventListener("click", async () => {
  document.getElementById("reportButton").click();
});

document.getElementById("menuButton").addEventListener("click", () => {
  document.getElementById("sidebar").classList.toggle("open");
  document.getElementById("overlay").classList.toggle("open");
});

document.getElementById("overlay").addEventListener("click", () => {
  document.getElementById("sidebar").classList.remove("open");
  document.getElementById("overlay").classList.remove("open");
});

document.querySelectorAll(".sidebar a[data-view]").forEach(link => {
  link.addEventListener("click", event => {
    event.preventDefault();
    const viewName = link.dataset.view;
    window.history.replaceState(null, "", `#${viewName}`);
    switchView(viewName);
  });
});

document.getElementById("refreshInterval").addEventListener("change", event => {
  refreshMs = Number(event.target.value);
  startRefreshTimer();
});

document.getElementById("trendWindow").addEventListener("change", event => {
  trendWindow = Number(event.target.value);
  redrawAll();
});

document.getElementById("dashboardDensity").addEventListener("change", event => {
  document.body.classList.toggle("compactDensity", event.target.value === "compact");
  requestAnimationFrame(() => redrawAll());
});

document.getElementById("pauseButton").addEventListener("click", event => {
  isPaused = !isPaused;
  event.target.textContent = isPaused ? "Resume Live Updates" : "Pause Live Updates";
  startRefreshTimer();
});

document.getElementById("generateSimulatorButton").addEventListener("click", async () => {
  const profile = document.getElementById("simulatorProfile").value;
  const seed = Number(document.getElementById("simulatorSeed").value || 42);
  const response = await fetch("/api/simulator/generate", {
    method: "POST",
    headers: { "Content-Type": "application/json" },
    body: JSON.stringify({ profile, seed }),
  });
  const result = await response.json();
  document.getElementById("modelOpsSummary").innerHTML = `
    <div><b>Simulator Loaded</b><span>${result.profile} profile, ${result.samples} samples.</span></div>
    <div><b>RUL Range</b><span>${result.rul_min_hours.toFixed(1)}h to ${result.rul_max_hours.toFixed(1)}h</span></div>
  `;
  await refresh();
});

document.getElementById("evaluateModelButton").addEventListener("click", async () => {
  const response = await fetch("/api/model/evaluate", {
    method: "POST",
    headers: { "Content-Type": "application/json" },
    body: JSON.stringify({ test_csv: "datasets/few_days_machine_dataset.csv" }),
  });
  const result = await response.json();
  document.getElementById("modelOpsSummary").innerHTML = `
    <div><b>Evaluation Samples</b><span>${result.samples} rows from ${result.test_csv}</span></div>
    <div><b>MAE / RMSE / R2</b><span>${result.metrics.mae.toFixed(2)} / ${result.metrics.rmse.toFixed(2)} / ${result.metrics.r2.toFixed(3)}</span></div>
  `;
});

window.addEventListener("hashchange", () => {
  switchView((location.hash || "#dashboard").replace("#", ""));
});

window.addEventListener("resize", () => {
  redrawAll();
});

setInterval(setUptime, 1000);
switchView((location.hash || "#dashboard").replace("#", ""));
refresh();
startRefreshTimer();
